name: Check KotlinGradle Code Changes

on:
  # 他のワークフローから呼べるようにする
  workflow_call:
    output:
      result:
        description: "KotlioGradleファイル変更チェック結果"
        value: ${{ jobs.check-kotlin-gradle.outputs.result }}

jobs:
  check-kotlin-gradle:
    name: Check KotlinGradle Code Changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Check for .gradle.kts changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            kotlin_gradle:
              - '**/*.gradle.kts'

      - name: Result
        id: result
        if: steps.filter.outputs.kotlin_gradle == 'true'
        run: |
          echo "✅ KotlioGradleファイルの更新がありました"
          echo "has_kotlin_gradle_changes=true" >> $GITHUB_OUTPUT
