name: Check Java Code Changes

on:
  # 他のワークフローから呼べるようにする
  workflow_call:
    outputs:
      result:
        description: "Javaファイル変更チェック結果"
        value: ${{ jobs.check-java.outputs.result }}

jobs:
  check-java:
    name: Check Java Code Changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Check for .java changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            result:
              - 'result/*.java'

      - name: Result
        id: result
        if: steps.filter.outputs.result == 'true'
        run: |
          echo "✅ Javaファイルの更新がありました"
          echo "result=true" >> $GITHUB_OUTPUT
