name: Check YAML Changes

on:
  # 他のワークフローから呼べるようにする
  workflow_call:
    outputs:
      result:
        description: "YAMLファイル変更チェック結果"
        value: ${{ jobs.check-yaml.outputs.result }}

jobs:
  check-yaml:
    name: Check YAML Changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Check for .yaml changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            result:
              - '**/*.yaml'
              - '**/*.yml'

      - name: Result
        id: result
        if: steps.filter.outputs.yaml == 'true'
        run: |
          echo "✅ YAMLファイルの更新がありました"
          echo "result=true" >> $GITHUB_OUTPUT
