name: JSON Formatter

on:
  pull_request:
    paths:
      - "**/*.json"
    types:
      - opened # PR作成時
      - synchronize # PRのコミット更新時

jobs:
  format-json:
    name: Format JSON
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          lfs: true

      - name: Format JSON Files with jq
        id: formatJson
        run: |
          # JSONファイルをフォーマットする
          find . -name "*.json" | while read file; do
            jq . "$file" > tmp.json && mv tmp.json "$file"
          done

      - name: Commit & Push
        id: commit_push
        if: steps.formatJson.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: JSONファイルをフォーマット"
